# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireExample
	pod 'Alamofire', '~> 5.0.0-beta.5'
end
